### ISSUE TITLE
Organise this code as a "standard package"

### ISSUE THREAD

**Issue by sylvaticus** [gideonsimpson/BasicMD.jl#2]
Hello, it seems you have [people trying to use your code](https://stackoverflow.com/questions/66230299/run-github-julia-code-using-jupyter-notebook), however it would be much better if yo uorganise it as a standard package (with Project.toml, tests, etc..) so you would not have to warry about adding directories to the path ;-)

You can have a look [here](https://syl1.gitbook.io/julia-language-a-concise-tutorial/language-core/11-developing-julia-packages) for a tutorial on how to implement your project as a Julia Package and register it.

**Comment by gideonsimpson** [comment]
On my to do list

**Comment by gideonsimpson** [comment]
This has been resolved in that one can now do:
```
 pkg> add https://github.com/gideonsimpson/JuBasicMD
```
I am not quite ready to add it to the general package registry.
